export const APPLICATION_STATUS = [
    "Applied",
    "Interview",
    "Offer",
    "Rejected",
    "Accepted"
];


// const sampleData = [ // sample data for graph 
//   // Jul 14
//   {
//     companyName: "Google",
//     role: "Frontend Developer",
//     location: "Remote",
//     salaryRange: "$120k-$140k",
//     companyLink: "https://google.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-14T09:00:00Z"),
//     updatedAt: new Date("2026-07-14T09:00:00Z"),
//   },
//   {
//     companyName: "Microsoft",
//     role: "Backend Developer",
//     location: "Hyderabad",
//     salaryRange: "$130k-$150k",
//     companyLink: "https://microsoft.com",
//     status: "Interview",
//     createdAt: new Date("2026-07-14T14:00:00Z"),
//     updatedAt: new Date("2026-07-14T14:00:00Z"),
//   },

//   // Jul 15
//   {
//     companyName: "Amazon",
//     role: "SDE I",
//     location: "Bangalore",
//     salaryRange: "$125k",
//     companyLink: "https://amazon.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-15T10:00:00Z"),
//     updatedAt: new Date("2026-07-15T10:00:00Z"),
//   },
//   {
//     companyName: "Netflix",
//     role: "React Developer",
//     location: "Remote",
//     salaryRange: "$160k",
//     companyLink: "https://netflix.com",
//     status: "Rejected",
//     createdAt: new Date("2026-07-15T13:00:00Z"),
//     updatedAt: new Date("2026-07-15T13:00:00Z"),
//   },
//   {
//     companyName: "Meta",
//     role: "Software Engineer",
//     location: "Remote",
//     salaryRange: "$170k",
//     companyLink: "https://meta.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-15T18:00:00Z"),
//     updatedAt: new Date("2026-07-15T18:00:00Z"),
//   },

//   // Jul 16
//   {
//     companyName: "Adobe",
//     role: "Frontend Engineer",
//     location: "Noida",
//     salaryRange: "$110k",
//     companyLink: "https://adobe.com",
//     status: "Interview",
//     createdAt: new Date("2026-07-16T09:00:00Z"),
//     updatedAt: new Date("2026-07-16T09:00:00Z"),
//   },
//   {
//     companyName: "Spotify",
//     role: "React Native Dev",
//     location: "Remote",
//     salaryRange: "$140k",
//     companyLink: "https://spotify.com",
//     status: "Offer",
//     createdAt: new Date("2026-07-16T12:00:00Z"),
//     updatedAt: new Date("2026-07-16T12:00:00Z"),
//   },

//   // Jul 17
//   {
//     companyName: "Uber",
//     role: "Full Stack Developer",
//     location: "Remote",
//     salaryRange: "$135k",
//     companyLink: "https://uber.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-17T11:00:00Z"),
//     updatedAt: new Date("2026-07-17T11:00:00Z"),
//   },
//   {
//     companyName: "Airbnb",
//     role: "Node.js Developer",
//     location: "Remote",
//     salaryRange: "$145k",
//     companyLink: "https://airbnb.com",
//     status: "Rejected",
//     createdAt: new Date("2026-07-17T15:00:00Z"),
//     updatedAt: new Date("2026-07-17T15:00:00Z"),
//   },
//   {
//     companyName: "Salesforce",
//     role: "Backend Engineer",
//     location: "Pune",
//     salaryRange: "$125k",
//     companyLink: "https://salesforce.com",
//     status: "Interview",
//     createdAt: new Date("2026-07-17T18:00:00Z"),
//     updatedAt: new Date("2026-07-17T18:00:00Z"),
//   },

//   // Jul 18
//   {
//     companyName: "Oracle",
//     role: "Java Developer",
//     location: "Bangalore",
//     salaryRange: "$115k",
//     companyLink: "https://oracle.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-18T09:00:00Z"),
//     updatedAt: new Date("2026-07-18T09:00:00Z"),
//   },
//   {
//     companyName: "IBM",
//     role: "Software Engineer",
//     location: "Remote",
//     salaryRange: "$105k",
//     companyLink: "https://ibm.com",
//     status: "Accepted",
//     createdAt: new Date("2026-07-18T16:00:00Z"),
//     updatedAt: new Date("2026-07-18T16:00:00Z"),
//   },

//   // Jul 19
//   {
//     companyName: "PayPal",
//     role: "Frontend Developer",
//     location: "Chennai",
//     salaryRange: "$118k",
//     companyLink: "https://paypal.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-19T10:00:00Z"),
//     updatedAt: new Date("2026-07-19T10:00:00Z"),
//   },
//   {
//     companyName: "Atlassian",
//     role: "React Developer",
//     location: "Remote",
//     salaryRange: "$150k",
//     companyLink: "https://atlassian.com",
//     status: "Interview",
//     createdAt: new Date("2026-07-19T15:00:00Z"),
//     updatedAt: new Date("2026-07-19T15:00:00Z"),
//   },

//   // Jul 20
//   {
//     companyName: "Intel",
//     role: "Embedded Engineer",
//     location: "Bangalore",
//     salaryRange: "$120k",
//     companyLink: "https://intel.com",
//     status: "Rejected",
//     createdAt: new Date("2026-07-20T09:00:00Z"),
//     updatedAt: new Date("2026-07-20T09:00:00Z"),
//   },
//   {
//     companyName: "Cisco",
//     role: "Network Engineer",
//     location: "Remote",
//     salaryRange: "$130k",
//     companyLink: "https://cisco.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-20T14:00:00Z"),
//     updatedAt: new Date("2026-07-20T14:00:00Z"),
//   },
//   {
//     companyName: "Stripe",
//     role: "Backend Engineer",
//     location: "Remote",
//     salaryRange: "$175k",
//     companyLink: "https://stripe.com",
//     status: "Offer",
//     createdAt: new Date("2026-07-20T18:00:00Z"),
//     updatedAt: new Date("2026-07-20T18:00:00Z"),
//   },

//   // Jul 21
//   {
//     companyName: "Twilio",
//     role: "Node Developer",
//     location: "Remote",
//     salaryRange: "$145k",
//     companyLink: "https://twilio.com",
//     status: "Interview",
//     createdAt: new Date("2026-07-21T10:00:00Z"),
//     updatedAt: new Date("2026-07-21T10:00:00Z"),
//   },
//   {
//     companyName: "Zoom",
//     role: "Frontend Developer",
//     location: "Remote",
//     salaryRange: "$140k",
//     companyLink: "https://zoom.us",
//     status: "Applied",
//     createdAt: new Date("2026-07-21T15:00:00Z"),
//     updatedAt: new Date("2026-07-21T15:00:00Z"),
//   },

//   // Jul 22-27
//   {
//     companyName: "Shopify",
//     role: "Full Stack",
//     location: "Remote",
//     salaryRange: "$150k",
//     companyLink: "https://shopify.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-22T11:00:00Z"),
//     updatedAt: new Date("2026-07-22T11:00:00Z"),
//   },
//   {
//     companyName: "Coinbase",
//     role: "Backend",
//     location: "Remote",
//     salaryRange: "$180k",
//     companyLink: "https://coinbase.com",
//     status: "Interview",
//     createdAt: new Date("2026-07-23T14:00:00Z"),
//     updatedAt: new Date("2026-07-23T14:00:00Z"),
//   },
//   {
//     companyName: "Figma",
//     role: "Frontend",
//     location: "Remote",
//     salaryRange: "$170k",
//     companyLink: "https://figma.com",
//     status: "Offer",
//     createdAt: new Date("2026-07-24T10:00:00Z"),
//     updatedAt: new Date("2026-07-24T10:00:00Z"),
//   },
//   {
//     companyName: "Canva",
//     role: "React Developer",
//     location: "Remote",
//     salaryRange: "$145k",
//     companyLink: "https://canva.com",
//     status: "Applied",
//     createdAt: new Date("2026-07-25T16:00:00Z"),
//     updatedAt: new Date("2026-07-25T16:00:00Z"),
//   },
//   {
//     companyName: "Datadog",
//     role: "Full Stack",
//     location: "Remote",
//     salaryRange: "$165k",
//     companyLink: "https://datadoghq.com",
//     status: "Accepted",
//     createdAt: new Date("2026-07-26T09:30:00Z"),
//     updatedAt: new Date("2026-07-26T09:30:00Z"),
//   },
//   {
//     companyName: "OpenAI",
//     role: "Software Engineer",
//     location: "Remote",
//     salaryRange: "$200k",
//     companyLink: "https://openai.com",
//     status: "Interview",
//     createdAt: new Date("2026-07-27T11:00:00Z"),
//     updatedAt: new Date("2026-07-27T11:00:00Z"),
//   },
// ];

// await Data.insertMany(sampleData);